[tox]
envlist = py312-django{42,52}, quality, docs
requires = tox-uv>=1

[pytest]
DJANGO_SETTINGS_MODULE = xblock.test.settings
addopts = --cov xblock
filterwarnings = always
norecursedirs = .* docs requirements

[testenv]
runner = uv-venv-lock-runner
dependency_groups =
    django42: django42
    django52: test
commands =
    python -Wd -m pytest {posargs:xblock}
    python -m coverage xml
allowlist_externals =
    make

[testenv:docs]
runner = uv-venv-lock-runner
basepython = python3.12
changedir = {toxinidir}/docs
dependency_groups = doc
commands =
    make html

[testenv:quality]
runner = uv-venv-lock-runner
dependency_groups = quality
changedir = {toxinidir}
commands =
    make quality

[pycodestyle]
ignore = E501,E402,E722
exclude = docs/*,.tox/,.venv/
