#! /bin/sh

# Fail immediately on errors
set -e

# Cache pip downloads
export PIP_DOWNLOAD_CACHE=${PIP_DOWNLOAD_CACHE-.pip_cache}

# Install requirements
pip install -r requirements.txt

# Allow django liveserver tests to use a range of ports
export DJANGO_LIVE_TEST_SERVER_ADDRESS=${DJANGO_LIVE_TEST_SERVER_ADDRESS-localhost:8000-9000}

# Run the tests
python manage.py test