#!/bin/bash
pylint xblock | tee /tmp/pylint-xblock.log
ERR=`grep -v "\*\*\*\*\*\*\*\*\*\*" /tmp/pylint-xblock.log | wc -l`
if [ $ERR -ge $1 ]; then
    echo "too many pylint violations: $ERR (max is $1)"
    exit 1
fi
